# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test Amplify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test Amplify
  pod 'GoogleSignIn'
  pod 'AWSMobileClient', '~> 2.10.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.10.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.10.0'   # Optional dependency required to use drop-in UI

end
